### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by valtermont** [smsaero/smsaero_api#1]
Мы пробовали использовать ваш SMS-шлюз, но к сожалению на Ubuntu 22.04 имеем проблемы с OpenSSL 3.0 - ошибка:

```
PHP Fatal error:  Uncaught Exception: Ошибка выполнения запроса: OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
```

Проблему смогли решить только откатом версии ОС в контейнере до гораздо более старой версии Debian-а, что для нашего прод-окружения не есть приемлемо.

**Comment by smsaero** [comment]
Спасибо за репорт. Проблема была вызвана различиями в обработке запросов, при использовании разных версий OpenSSL ни клиенте и сервере — решено.
